README.md
Sodium.podspec

Sorry for the confusion @jedisct1.
I have renamed the podspec from `swift-sodium` to `Sodium` as it will be easier for the user to use it as described in the documentation. 
Now dev can add `import Sodium`, otherwise he has to use `import swift_sodium`, which isn't so nice.
Also I wasn't sure about the license, so you might want to set the correct license like: `s.license     = { :type => "MIT", :file => 'LICENSE' }`
Also, you will have to push the podspec to the CocoaPods servers, as you are the owner.
For now users can use it like:
```
pod 'swift-sodium', git: 'https://github.com/jedisct1/swift-sodium.git', :branch => 'master'
```

Renamed podspec for cocoapods

---

Sodium/Box.swift
SodiumTests/SodiumTests.swift

I am adding support for separate beforenm and afternm operates, for pre-generating the shared secret for slightly better performance and potential use of the shared secret in other contexts.

Support for beforenm and afternm

---

Sodium/Box.swift
Sodium/GenericHash.swift
Sodium/PWHash.swift
Sodium/RandomBytes.swift
Sodium/SecretBox.swift
Sodium/ShortHash.swift
Sodium/Sign.swift
Sodium/Utils.swift

Swift 2 introduced the guard keyword which can be used to early exits.
Adopting it makes the code a little bit cleaner (although less cheerful, without all the exclamation marks :)

Adopts guard syntax for early exits

---

README.md
Sodium/Box.swift
SodiumTests/SodiumTests.swift

This PR adds seal() and open() funcs for crypto_box_seal and crypto_box_open, allowing one to anonymously send messages to a recipient given its public key. (docs here: http://doc.libsodium.org/public-key_cryptography/sealed_boxes.html )
I won't quibble too much but it did throw me for a loop that you used the seal verb without actually exposing libsodium's seal method. 😜

added func overloads for anonymous seal and open

---

Sodium.xcodeproj/project.pbxproj
Sodium/NSData+Extensions.swift

- The NSData and NSMutableData are now public (That's why I renamed the
file)
- With this change, whenever we need to extend the lib, we can use the
same methods as Sodium to access the data pointers instead needing to
duplicate this code.

Changes `InternalExtensions` to `NSData+Extensions`

---

README.md

`.toData()` isn't implemented on `String` and `.scrypt` was missing from `sodium.pwHash.*`
Using it like this seems to work fine 😊

Fix swift code in password hashing example

---

Sodium/Box.swift
Sodium/Sign.swift

In this case, I find Swift's access levels a bit confusing. The implicitly created (or "default") initializer has the access level `internal` and can therefore not be used outside of the library, even though all members and the `struct` is marked as `public`.
This is not a real issue as the Sodium API takes `PublicKey` or `SecretKey` instances rather than `KeyPair`s. But it would be nice to be able to re-use the `KeyPair` struct after persisting keys without the need to extend it manually.
> A default initializer has the same access level as the type it initializes, unless that type is defined as `public`. For a type that is defined as `public`, the default initializer is considered internal. If you want a public type to be initializable with a no-argument initializer when used in another …

Add public initializers to KeyPair structs

---

SodiumTests/SodiumTests.swift

This removes three warnings from the build, and it's probably not bad to check the result there to see if the operation succeeded.
The warnings were:
> Result of call to update(input:) is unused.

Fix warnings for unused results

---

README.md
Sodium.xcodeproj/project.pbxproj
SodiumTests/ReadmeTests.swift

Update README.md examples so that they will compile.  Added ReadmeTests.swift to verify these snippets.
A lot of changes to the snippet include the addition of first argument names and " as NSData".  I know many of these are addressed in #48, and I'll be very happy to rebase and redo this PR if those changes are merged.

Update README.md examples so that they will compile

---

README.md
SodiumTests/ReadmeTests.swift

First I removed some empty spaces that where inconsistent with the rest of the code.
Second I added some `XCTAssert…()` statements to avoid warnings about unused variables for the tests for the example code. I only removed the warnings for examples without modifying them, so some superfluous warnings are still showing up.
I tried adding `-Wno-unused-variables` as a compiler flag to `ReadmeTests.swift` but this does not work for Swift 3 apparently (see multiple SO answers).

Reduce compiler warnings for example tests

---

README.md
Sodium.xcodeproj/project.pbxproj
Sodium/KeyExchange.swift
Sodium/Sodium.swift
SodiumTests/SodiumTests.swift

This adds the key exchange functionality of libsodium to swift-sodium.
As I wanted to keep the structure of lib sodium, this PR introduces a new class KeyExchange with the following method:
```
func sessionKeyPair(publicKey: PublicKey, secretKey: SecretKey, otherPublicKey: PublicKey, side: Side) -> SessionKeyPair?
```
See https://github.com/jedisct1/swift-sodium/pull/60 and [libsodium.org/doc/key_exchange](https://download.libsodium.org/doc/key_exchange/)

Add key exchange

---

Sodium.xcodeproj/xcshareddata/xcschemes/Sodium.xcscheme

I think it is safe and useful to enable this for unit tests.

Collect coverage data from unit tests

---

Sodium.xcodeproj/project.pbxproj

The file `Auth.swift` was not included in the `Sodium_OSX` target, which led to a build failure.

Fix building on macOS

---

Sodium.podspec

see issue #75 
This pull-request should fix missing files by using Pods, since the libsodium core was moved from `Sodium` to `Sodium/libsodium`.

fixes podspec source paths

---

Sodium.xcodeproj/project.pbxproj

The `libsodium` module cannot be imported, as it is not found. I assume it is due to missing search paths.
This is a blind fix for issue #75, as I was not able to reproduce it.

Fix Swift import search path

---

Sodium.podspec

Sadly the proposed solution from #77 did not work for Cocoa-Pods, but the Idea was the right one.
The Podspec file just had to adapt the fixed `SWIFT_INCLUDE_PATHS`.
This should now solve all build issues with CocoaPods. Original issue see #75.

fixes build-issues using Cocoa Pods

---

README.md
Sodium/Box.swift
SodiumTests/SodiumTests.swift

It's been a breeze to work with swift-sodium. Thanks so much for your work.
I am working on a BLE encryption for which the peer device requires a very specific nonce. This PR adds the ability to swift-sodium's `Box` for a user to provide his own nonce instead of relying on `self.nonce()` to generate a random encryption nonce.
Thanks!

add `Box.open()` overload that takes a user-specified nonce

---

SodiumTests/SodiumTests.swift

This makes some changes to the tests that were added lately:
- Hard-coded numbers are avoided
- Key derivation test is now based on logic rather than specific values
- Some code cleanup

Cleanup and improve recent tests

---

Sodium.xcodeproj/project.pbxproj

When building the "SodiumTests" target the following warning was issued:
> `ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/Developer/Library/Frameworks'`
I validated that there is no such path in my Xcode installation and removed the framework search path accordingly. Since building succeeds anyway it looks like this is not required.

Fix warning

---

Sodium/Auth.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Stream.swift
Tests/SodiumTests/ReadmeTests.swift
Tests/SodiumTests/SodiumTests.swift

Returning a non-optional value saves the client code from unnecessary
error checking or generous use of force-unwraps.

Return non-optional key if keygen is guaranteed to succeed

---

README.md
Sodium/Auth.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Stream.swift
Tests/SodiumTests/ReadmeTests.swift
Tests/SodiumTests/SodiumTests.swift

Returning a non-optional value saves the client code from unnecessary
error checking or generous use of force-unwraps.
This is a revised version of #125 which got reverted in #129 due to the
README not being updated.

Return non-optional key if keygen is guaranteed to succeed (with docs)

---

Sodium/Aead.swift
Sodium/Box.swift
Sodium/GenericHash.swift
Sodium/RandomBytes.swift
Sodium/SecretBox.swift
Sodium/Stream.swift
Sodium/Utils.swift

Swift 4.1 introduces warnings when mutable variables are accessed in a way where they may be modified and are simultaneously read. e.g. when using `noncePtr` and `nonce.count` here:
https://github.com/jedisct1/swift-sodium/blob/8df5a4a75a3b6088351362b5b6f2c2a93071b26f/Sodium/Aead.swift#L37
I've added local length constants where the length of a `Data` value was calculated from an instance variable in an attempt to make it harder to mismatch the init length with this stored constant. I've also added local length constants the length was calculated in-place for the same reason. Where a local variable or constant was available I've used it.
There are additional warnings present in Swift 4.1 due to [SE-0184](https://github.com/apple/swift-evolution/blob/master/proposals/0184-unsafe-pointers-ad …

Use constant local variables in-place of computed property of mutable value

---

Sodium/Auth.swift
Sodium/Box.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/KeyExchange.swift
Sodium/PWHash.swift
Sodium/RandomBytes.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Sign.swift
Sodium/Sodium.swift
Sodium/Stream.swift
Sodium/Utils.swift

Guard statements come with the added compiler check that the body of the `else { ... }` statement returns to the parent scope or otherwise does not permit falling through (e.g. via a return, throwing, calling a function with return type `Never` etc...) which makes them perfect for asserting a condition is true for the remainder of the function body.
IMO they also tend to just "work better in practice", for example in `KeyDerivation.swift`:
```diff
-        if length < BytesMin || length > BytesMax {
-            return nil
-        }
-        if secretKey.count != KeyBytes {
-            return nil
-        }
-        var contextBin = context.data(using: String.Encoding.utf8)!
-        if contextBin.count > ContextBytes {
-            return nil
-        }
+        guard …
```

Use guards where intention is to return

---

Sodium.xcodeproj/project.pbxproj
Sodium/GenericHash.swift
Sodium/SecretStream.swift
Sodium/StateStream.swift

There are a few classes (`GenericHash.Stream`, `SecretStream.XChaCha20Poly1305.PushStream`, and `SecretStream.XChaCha20Poly1305.PullStream`) which have some very similar internal behaviour which boils down to picking a types and specifying a value.
Using a new `StateStream` protocol we can allow these implementations to just specify this information and have `free()` and state generation be taken care of by a protocol extension.
I've also removed the optional wrapper around `state` since 1. the `.some` state was forced unwrapped in almost all of its use (either explicitly with `!` or implicitly via use of the C API); 2. all calls to `free()` were made right before the `StateStream` object was deinitialised or failed to initialise – either way – there would be no subsequent direct access …

State stream protocol

---

Sodium.xcodeproj/project.pbxproj
Sodium/Aead.swift
Sodium/Auth.swift
Sodium/Box.swift
Sodium/ExitCode.swift
Sodium/Generators/KeyPairGenerator.swift
Sodium/Generators/KeyPairProtocol.swift
Sodium/Generators/NonceGenerator.swift
Sodium/Generators/SecretKeyGenerator.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/KeyExchange.swift
Sodium/PWHash.swift
Sodium/RandomBytes.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Sign.swift
Sodium/Stream.swift
Sodium/Utils.swift
Tests/SodiumTests/SodiumTests.swift

This is based on #141, so please ignore commits before 04a17eb. (actual diff: https://github.com/aidantwoods/swift-sodium/compare/readability/a-few-small-tweaks...aidantwoods:enhancement/protocol-abstractions)
This adds several protocols with accompanying default implementations to remove some common duplicated patterns.

Protocol abstractions

---

Tests/SodiumTests/ReadmeTests.swift
Tests/SodiumTests/SodiumTests.swift

I'm not really sure why this is allowed in Swift 4.1

Force unwrap where required in tests

---

Sodium.xcodeproj/project.pbxproj

On master the current target Sodium_OSX fails due to a missing dependency to Aead.swift.
This PR takes the file into consideration in the build.

Include Aead in build for OSX target

---

Sodium/Utils.swift
Tests/SodiumTests/ReadmeTests.swift
Tests/SodiumTests/SodiumTests.swift

So I reread the [docs](https://download.libsodium.org/doc/helpers/padding.html) on the padding function and it appears I was somehow confusing myself before. Byte values that lie further than the unpadded length shouldn't matter and won't cause the padding function to be confused about where the content ends because we of course tell it the unpadded length (for some reason I was worrying about this).
In this case, appending a block worth of zeros to the byte array should be sufficient, and then of course trimming to the padded length after we know it.
This also renames an argument label where I forgot it.

Remove explicit pointer use from padding

---

Sodium/Aead.swift
Sodium/Auth.swift
Sodium/Box.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/KeyExchange.swift
Sodium/PWHash.swift
Sodium/RandomBytes.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Sign.swift
Sodium/Sodium.swift
Sodium/Stream.swift
Sodium/Utils.swift

In Swift we have [value types](https://developer.apple.com/videos/play/wwdc2015/408), so classes are often overkill – I've left them in for now for things implementing `StateStream` because they directly hold onto a pointer and we want to proactively free our internal state when deinitialisation occurs. For everything else, we don't need classes :)
I've also segmented each document into (IMO) some sensible groups by utilising extensions to implement each section of the types.

Convert to structs where possible and file segmentation

---

Sodium/Aead.swift
Sodium/Auth.swift
Sodium/Box.swift
Sodium/Generators/KeyPairGenerator.swift
Sodium/Generators/KeyPairProtocol.swift
Sodium/Generators/NonceGenerator.swift
Sodium/Generators/SecretKeyGenerator.swift
Sodium/GenericHash.swift
Sodium/KeyDerivation.swift
Sodium/KeyExchange.swift
Sodium/SecretBox.swift
Sodium/SecretStream.swift
Sodium/ShortHash.swift
Sodium/Sign.swift
Sodium/Stream.swift

This is a quick stopgap to fix https://github.com/jedisct1/swift-sodium/issues/152 where dynamic linking of release builds fail because of Swift compiler issues around a public class conforming to an internal protocol.

Make KeyPairGenerator and KeyPairProtocol and related public

---

Sodium.xcodeproj/project.pbxproj
Sodium/GenericHash.swift
Sodium/SecretStream.swift
Sodium/StateStream.swift

The [`StateStream`](https://github.com/jedisct1/swift-sodium/blob/d918fdbfe95879b1a7c78a9607bc1a03a45fcf22/Sodium/StateStream.swift) protocol (added in #140) is probably now redundant due to the work on removing pointers in #148 (which removed the need for the shared memory freeing methods).
It is possible that it would be desirable to keep the protocol to highlight the structural similarity among the various streams—however the protocol is no longer required for the code sharing (this was the original motivation for adding it).

Remove redundant state stream protocol

---

Sodium.podspec

Completing the work of #168 and #169, this PR adds watchOS support to the Podspec.

Add watchOS to Podspec

---

Examples/CommonCode/Helpers.swift
Sodium.xcodeproj/project.pbxproj

Add `#availability` checks to ensure examples are Xcode 10.2 compatible.

Ensure examples compile on Xcode 10.2

---

README.md
Sodium/SecretBox.swift
Tests/SodiumTests/SodiumTests.swift

As good as the current API is at some times it is necessary to have
reproducible results of the encryption. This commit introduces:
```
sodium.secureBox.seal(message: [...], secretKey: [...], nonce: [...])
```
That takes the usual `message` and `secretKey`, and an additional
user-provided `nonce` to generate the result that is completely defined
by those inputs and does not rely on any entropy.

Add nonce-accepting overload of `secretBox.seal`

---

Sodium.podspec

This restores CocoaPods compatibility using the xcframework-based copy of Clibsodium but there are a few things to note:
- CocoaPods prior to 1.10.0 (current version is 1.10.0.rc.1) did not support XCFrameworks which wrap .a static libraries
- CocoaPods currently also has a bug where it in some circumstances, it uses the XCFramework's name for the `-l` linking flag (i.e. `-lClibsodium` instead of the correct library name (`-lsodium`). I've made a PR to fix that at https://github.com/CocoaPods/CocoaPods/pull/10072 and expect it to be merged shortly, before a final version of 1.10.0 is released.
- Meanwhile, in Xcode 12, `arm64` is a valid architecture for iOS and watchOS _simulator_ builds (because arm-based Macs), and is included in the default simulator architectures lists. …

Fix the podspec to get it working with the XCFramework

---

Package.swift

This PR:
- Sets `swift-tools-version` in `Package.swift` to 5.0 (to match `swift_version` setting in `Sodium.podspec`).
**N.B:**
- Reducing the `swift-tools-version` setting from 5.3 to 5.0 (to match the podspec file) also allows the library to be integrated using the 'Swift Packages' integration present in Xcode 11.x and above. (Whereas leaving it set at 5.3 meant that Xcode 12.x and above was required).

Ensure Package.swift and Sodium.podspec both specify Swift 5.0

---

.gitignore
Examples/tvOS/AppDelegate.swift
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
Examples/tvOS/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
Examples/tvOS/Assets.xcassets/Contents.json
Examples/tvOS/Base.lproj/LaunchScreen.storyboard
Examples/tvOS/Base.lproj/tvOSMain.storyboard
Examples/tvOS/Info.plist
Examples/tvOS/ViewController.swift
Sodium.xcodeproj/project.pbxproj
Sodium.xcodeproj/xcshareddata/xcschemes/Sodium_iOS.xcscheme
Sodium.xcodeproj/xcshareddata/xcschemes/Sodium_tvOS.xcscheme
Sodium.xcodeproj/xcshareddata/xcschemes/Sodium_watchOS.xcscheme

This PR adds tvOS support, specifically the following are added:
- Adds `Sodium_tvOS` framework build target and scheme.
- Adds `Example tvOS` app build target and scheme
- This uses the same code as the `Example iOS` app in `ViewController.swift` to test that basic functionality is working as expected when running on tvOS.

Add tvOS support

---

Package.swift

This PR is effectively a revert of the PR https://github.com/jedisct1/swift-sodium/pull/215 (which was made in error it turns out):
- Sets `// swift-tools-version:5.3` in `Package.swift` since `.binaryTarget(…)` is only available in Xcode 12.0 and above.

Resolve Xcode 12 Package manifest resolution error

---

Clibsodium/module.modulemap
Clibsodium/shim.h
Package.swift

This is not quite a solution for the problem of #224, but it's a running workaround. Otherwise, swift-sodium can't be used on server side projects on Linux - this makes it possible again.

Use xcframework only for supported OS

---

Package.swift

Unfortunately, a swift bug makes it impossible to use swift-sodium on linux. The fix is really quick and easy.
The bug is the following: https://bugs.swift.org/browse/SR-14038

Circumvent swift bug SR-14038

---

Tests/SodiumTests/SodiumTests.swift

Added test vectors for ed25519 from RFC8032: https://datatracker.ietf.org/doc/html/rfc8032#section-7.1

Add test vectors from RFC8032 for ed25519 signatures
